version : '3.4'

services: 
  orion:
    container_name: orion_node
    image: pegasyseng/orion:${ORION_VERSION}
    volumes:
      - ./config/orion:/opt/orion/conf/
      - ./data/orion:/opt/orion/data
    command: ["/opt/orion/conf/orion.conf"]
    ports:
      - 8888:8888
      - 8080:8080
    networks:
      main:
        ipv4_address: 172.16.2.21

  orion2:
    container_name: orion_node2
    image: pegasyseng/orion:${ORION_VERSION}
    volumes:
      - ./config/orion2:/opt/orion/conf/
      - ./data/orion2:/opt/orion/data
    command: ["/opt/orion/conf/orion.conf"]
    ports:
      - 8889:8888
      - 8081:8080
    networks:
      main:
        ipv4_address: 172.16.2.22

  orion3:
    container_name: orion_node3
    image: pegasyseng/orion:${ORION_VERSION}
    volumes:
      - ./config/orion3:/opt/orion/conf/
      - ./data/orion3:/opt/orion/data
    command: ["/opt/orion/conf/orion.conf"]
    ports:
      - 8890:8888
      - 8082:8080
    networks:
      main:
        ipv4_address: 172.16.2.23

  besu: 
    container_name: besu_node
    image: hyperledger/besu:${BESU_VERSION}
    volumes:
      - ./config/besu:/opt/besu/conf/
      - ./data/besu:/opt/besu/data/
    command : [
      "--config-file=/opt/besu/conf/besu.conf",
      "--privacy-enabled=${PRIVACY_ENABLED}",
      "--permissions-accounts-contract-enabled=${PERMISSIONING_ENABLED}",
      "--permissions-nodes-contract-enabled=${PERMISSIONING_ENABLED}"
    ]
    ports :
      - 8515:8545
      - 8516:8546
      - 8517:8547
    networks:
      main:
        ipv4_address: 172.16.2.11
    depends_on:
      - orion
    
  besu2: 
    container_name: besu_node2
    image: hyperledger/besu:${BESU_VERSION}
    volumes:
      - ./config/besu2:/opt/besu/conf/
      - ./data/besu2:/opt/besu/data/
    command : [
      "--config-file=/opt/besu/conf/besu.conf",
      "--privacy-enabled=${PRIVACY_ENABLED}",
      "--permissions-accounts-contract-enabled=${PERMISSIONING_ENABLED}",
      "--permissions-nodes-contract-enabled=${PERMISSIONING_ENABLED}"
    ]
    ports :
      - 8525:8545
      - 8526:8546
      - 8527:8547
    networks:
      main:
        ipv4_address: 172.16.2.12
    depends_on:
      - orion2
  
  besu3:
    container_name: besu_node3
    image: hyperledger/besu:${BESU_VERSION}
    volumes:
      - ./config/besu3:/opt/besu/conf/
      - ./data/besu3:/opt/besu/data/
    command : [
      "--config-file=/opt/besu/conf/besu.conf",
      "--privacy-enabled=${PRIVACY_ENABLED}",
      "--permissions-accounts-contract-enabled=${PERMISSIONING_ENABLED}",
      "--permissions-nodes-contract-enabled=${PERMISSIONING_ENABLED}"
    ]
    ports :
      - 8535:8545
      - 8536:8546
      - 8537:8547
    networks:
      main:
        ipv4_address: 172.16.2.13
    depends_on:
      - orion3

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/27